### ISSUE TITLE
Delete all pics with one button

### ISSUE THREAD

**Issue by 1gzify** [MythicalLTD/MythicalPics#1]

**Comment by superhoridev** [comment]
Hello, the button was added, it is 50% done as i didn't choose a definitive placement for it, you just need to do a git pull or git clone on your server for the web app and it will update

Edit: i forgot to tell you, there is no warning before pressing the button, when you do, all photos are gone, all at once

**Comment by superhoridev** [comment]
The button was completed, its definitive position is in admin panel into the settings tab at the bottom, now the button prompts for a confirmation before deleting all the images
